# File: .github/workflows/repo-sync.yml
name: repo-sync
on:
  schedule:
    - cron: '1 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync-Script-LYM
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync ziye12-JavaScript
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ziye66666/JavaScript.git"
          source_branch: "main"
          destination_branch: "ziye12"
          github_token: ${{ secrets.PAT }}
      - name: sync Sunert-Scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Sunert/Scripts.git"
          source_branch: "master"
          destination_branch: "Sunert"
          github_token: ${{ secrets.PAT }}
          